[project]
name = "python"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "psycopg>=3.3.2",
    "pytest>=9.0.2",
    "testcontainers[postgres,kafka]>=4.13.3",
    "confluent-kafka>=2.7.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
filterwarnings = ["ignore::DeprecationWarning"]
